name: Deploy FASTAPI Backend to Production

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Git commit hash
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set environment
        run: echo "ENV=production" >> $GITHUB_ENV

      - name: Create .env file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
          echo "REDIS_URL=${{ secrets.REDIS_URL }}" > .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" > .env
          echo "ALGORITHM=${{ secrets.ALGORITHM }}" > .env
          echo "ACCESS_TOKEN_EXPIRE_MINUTES=${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}" > .env

      - name: Login to Vultr Container Registry
        uses: docker/login-action@v3
        with:
          registry: ewr.vultrcr.com
          username: ${{ secrets.VULTR_REGISTRY_USERNAME }}
          password: ${{ secrets.VULTR_REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ewr.vultrcr.com/apiregistry/fastapi-app:${{ env.ENV }}-${{ env.SHORT_SHA }} .

      - name: Push Docker image to Vultr Container Registry
        run: |
          docker push ewr.vultrcr.com/apiregistry/fastapi-app:${{ env.ENV }}-${{ env.SHORT_SHA }}

      - name: Copy deployment files to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_PRIVATE_KEY }}
          password: ${{ secrets.VM_PASSWORD }}
          source: "docker-compose.yml,deploy.sh,.env"
          target: "/home/${{ secrets.VM_USER }}/app"

      - name: SSH into VM and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.VM_USER }}/app
            bash ./deploy.sh ${{ env.SHORT_SHA }} ${{ env.ENV }}
